development:
  sessions:
    default:
      database: top_denton_development
      hosts:
        - localhost:27017
      options:
  options:
test:
  sessions:
    default:
      database: top_denton_test
      hosts:
        - localhost:27017
      options:
        consistency: :strong
        max_retries: 1
        retry_interval: 0
production:
  sessions:
    default:
      database: top_denton
      hosts:
        - localhost:27017
      options:
        consistency: :strong
  options:
