development:
  sessions:
    default:
      database: top_denton_development
      hosts:
        - localhost:27017
      options:
  options:
test:
  sessions:
    default:
      database: top_denton_test
      hosts:
        - localhost:27017
      options:
        consistency: :strong
        max_retries: 1
        retry_interval: 0
production:
  sessions:
    default:
      database: top_denton
      hosts:
        - 192.241.214.127:27017
        - 192.241.212.23:27017
        - 192.241.220.139:27017
      options:
  options:
